import './core';
import initSmoothScroll from './smooth-scroll';
import initReveal from './reveal';
import initCounter from './counter';
import initTerminals from './terminal';
import initMousePreview from './mouse-preview';
import initMagnetic from './magnetic';
import initSectionNav from './section-nav';
import initPipeline from './pipeline';
import initHeroField from './hero-field';

initSmoothScroll();
initReveal();
initCounter();
initTerminals();
initMousePreview();
initMagnetic();
initSectionNav();
initPipeline();
initHeroField();
