import './core';
import initSmoothScroll from './smooth-scroll';
import initReveal from './reveal';
import initCounter from './counter';
import initMousePreview from './mouse-preview';
import initMagnetic from './magnetic';
import initSectionNav from './section-nav';
import initPipeline from './pipeline';
import initPromise from './promise';
import initHeroField from './hero-field';
import initWhatIDo from './what-i-do';

initSmoothScroll();
initReveal();
initCounter();
initMousePreview();
initMagnetic();
initSectionNav();
initPipeline();
initPromise();
initHeroField();
initWhatIDo();
