import './core';
import initSmoothScroll from './smooth-scroll';
import initReveal from './reveal';
import initCounter from './counter';
import initWorkPanel from './work-panel';
import initMagnetic from './magnetic';
import initSectionNav from './section-nav';
import initPipeline from './pipeline';
import initPromise from './promise';
import initHeroRelief from './hero-relief';
import initWhatIDo from './what-i-do';

initSmoothScroll();
initReveal();
initCounter();
initWorkPanel();
initMagnetic();
initSectionNav();
initPipeline();
initPromise();
initHeroRelief();
initWhatIDo();
